<?php
/**
 * Single Post Template
 *
 * @package Affos
 * @since 1.0.0
 */

get_header();

while (have_posts()) : the_post();
    $post_id = get_the_ID();
    
    // Get category
    $categories = get_the_category();
    $category_name = !empty($categories) ? $categories[0]->name : '';
    $category_slug = !empty($categories) ? $categories[0]->slug : '';

    // Badge class
    $badge_class = '';
    if (strpos($category_slug, 'tips') !== false) {
        $badge_class = 'tips';
    } elseif ($category_slug === 'tutorial') {
        $badge_class = 'tutorial';
    } elseif (strpos($category_slug, 'opini') !== false) {
        $badge_class = 'opinion';
    }

    // Get author info
    $author_id = get_the_author_meta('ID');
    $author_name = get_the_author_meta('display_name');
    $author_bio = get_the_author_meta('description');

    // Reading time
    $content = get_the_content();
    $word_count = str_word_count(strip_tags($content));
    $reading_time = max(1, ceil($word_count / 200));
?>

<!-- Post Header -->
<section class="post-header">
    <div class="container">
        <div class="post-breadcrumb">
            <a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Beranda', 'affos'); ?></a>
            <i class="ri-arrow-right-s-line"></i>
            <?php
            $blog_page = get_option('page_for_posts');
            $blog_url = $blog_page ? get_permalink($blog_page) : home_url('/blog/');
            ?>
            <a href="<?php echo esc_url($blog_url); ?>"><?php esc_html_e('Blog', 'affos'); ?></a>
            <i class="ri-arrow-right-s-line"></i>
            <span><?php the_title(); ?></span>
        </div>

        <div class="post-header-content">
            <?php if ($category_name) : ?>
                <span class="post-cat-badge <?php echo esc_attr($badge_class); ?>"><?php echo esc_html($category_name); ?></span>
            <?php endif; ?>
            <h1><?php the_title(); ?></h1>
            <?php if (has_excerpt()) : ?>
                <p class="post-header-excerpt"><?php echo esc_html(get_the_excerpt()); ?></p>
            <?php endif; ?>
            <div class="post-header-meta">
                <div class="post-author-info">
                    <div class="author-avatar-lg">
                        <?php echo get_avatar($author_id, 48); ?>
                    </div>
                    <div class="author-details">
                        <span class="author-name"><?php echo esc_html($author_name); ?></span>
                        <span class="author-role"><?php esc_html_e('Affos Editorial', 'affos'); ?></span>
                    </div>
                </div>
                <div class="post-meta-info">
                    <span class="post-date"><i class="ri-calendar-line"></i> <?php echo get_the_date(); ?></span>
                    <span class="post-read-time"><i class="ri-time-line"></i> <?php printf(__('%d min read', 'affos'), $reading_time); ?></span>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Post Hero Image -->
<?php if (has_post_thumbnail()) : ?>
<section class="post-hero-image">
    <div class="container">
        <div class="hero-image-wrapper">
            <?php the_post_thumbnail('full', array('class' => 'hero-image')); ?>
        </div>
    </div>
</section>
<?php endif; ?>

<!-- Post Content -->
<section class="post-content-section">
    <div class="container">
        <div class="post-layout">
            <!-- Sidebar -->
            <aside class="post-sidebar">
                <!-- Table of Contents -->
                <div class="sidebar-card toc-card">
                    <h4><i class="ri-list-unordered"></i> <?php esc_html_e('Daftar Isi', 'affos'); ?></h4>
                    <nav class="toc-nav" id="toc-nav">
                        <!-- Generated by JavaScript -->
                    </nav>
                </div>

                <!-- Share -->
                <div class="sidebar-card share-card">
                    <h4><?php esc_html_e('Bagikan Artikel', 'affos'); ?></h4>
                    <div class="share-buttons">
                        <a href="https://twitter.com/intent/tweet?url=<?php echo urlencode(get_permalink()); ?>&text=<?php echo urlencode(get_the_title()); ?>" target="_blank" rel="noopener" class="share-btn twitter">
                            <i class="ri-twitter-x-line"></i>
                        </a>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode(get_permalink()); ?>" target="_blank" rel="noopener" class="share-btn facebook">
                            <i class="ri-facebook-fill"></i>
                        </a>
                        <a href="https://wa.me/?text=<?php echo urlencode(get_the_title() . ' ' . get_permalink()); ?>" target="_blank" rel="noopener" class="share-btn whatsapp">
                            <i class="ri-whatsapp-line"></i>
                        </a>
                        <button class="share-btn copy" onclick="navigator.clipboard.writeText('<?php echo esc_js(get_permalink()); ?>')">
                            <i class="ri-link"></i>
                        </button>
                    </div>
                </div>

                <!-- Newsletter -->
                <div class="sidebar-card newsletter-card">
                    <h4><i class="ri-mail-line"></i> <?php esc_html_e('Newsletter', 'affos'); ?></h4>
                    <p><?php esc_html_e('Dapatkan update terbaru langsung ke inbox Anda.', 'affos'); ?></p>
                    <form class="newsletter-form" action="#" method="post">
                        <input type="email" placeholder="<?php esc_attr_e('Email Anda', 'affos'); ?>" required>
                        <button type="submit" class="btn btn-primary btn-sm"><?php esc_html_e('Langganan', 'affos'); ?></button>
                    </form>
                </div>
            </aside>

            <!-- Main Article -->
            <article class="post-article">
                <div class="article-content">
                    <?php the_content(); ?>
                </div>

                <!-- Tags -->
                <?php
                $tags = get_the_tags();
                if ($tags) :
                ?>
                <div class="article-tags">
                    <span class="tags-label"><?php esc_html_e('Tags:', 'affos'); ?></span>
                    <?php foreach ($tags as $tag) : ?>
                        <a href="<?php echo esc_url(get_tag_link($tag->term_id)); ?>" class="tag"><?php echo esc_html($tag->name); ?></a>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>

                <!-- Author Box -->
                <div class="author-box">
                    <div class="author-avatar-xl">
                        <?php echo get_avatar($author_id, 80); ?>
                    </div>
                    <div class="author-content">
                        <h4><?php esc_html_e('Tentang Penulis', 'affos'); ?></h4>
                        <h5><?php echo esc_html($author_name); ?></h5>
                        <?php if ($author_bio) : ?>
                            <p><?php echo esc_html($author_bio); ?></p>
                        <?php else : ?>
                            <p><?php esc_html_e('Kontributor di Affos dengan fokus pada review gadget dan teknologi terkini.', 'affos'); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
            </article>
        </div>
    </div>
</section>

<!-- Related Posts -->
<section class="related-posts">
    <div class="container">
        <h2 class="section-title"><?php esc_html_e('Artikel Terkait', 'affos'); ?></h2>
        <div class="blog-grid">
            <?php
            $related = get_posts(array(
                'post_type'      => 'post',
                'posts_per_page' => 3,
                'post__not_in'   => array($post_id),
                'category__in'   => wp_list_pluck($categories, 'term_id'),
            ));

            foreach ($related as $post) {
                get_template_part('template-parts/card', 'blog', array('post' => $post));
            }
            wp_reset_postdata();
            ?>
        </div>
    </div>
</section>

<?php
endwhile;
get_footer();
